# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CMake@1
  inputs:
    workingDirectory: '.'
    cmakeArgs: '-S . -B ./build -G "Visual Studio 16 2019"'
  displayName: 'cmake'

- task: MSBuild@1
  inputs:
    solution: 'build/OpenCV.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'


- task: MSBuild@1
  inputs:
    solution: 'build/OpenCV.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Debug'
